Header downloader - step 1 (#331)
* Initial header downloader implementation
- structure & threading model
- gRPC handling
- inbound GetBlockHeaders, NewBlockHashes (partial impl)
- outbound GetBlockHeaders (partial impl)
- rpc SetStatus, SendMessageById, SendMessageByMinBlock
(squashed commit of external branch)

* * Respond to external requests, use new sentry interface, rlp encode/decode all messages (eth/66)
Status:
- (complete impl) inbound GetBlockBodies, GetBlockHeaders
- (partial impl) inbound BlockHeaders, NewBlock, NewBlockHashes
- (partial impl) outbound GetBlockHeaders
- rpc SetStatus, SendMessageById, SendMessageByMinBlock, PeerMinBlock, ReceiveMessages
- packets (rlp encoding & test) BlockBodies, BlockHeaders, GetBlockBodies, GetBlockHeaders, NewBlockHashes, NewBlock
(squashed commit of external branch)

* Fix

* Remove the "chain reconstruction" from the downloader and leave only the peer's requests processing

* Separate stage interface from active component interface

* Switch from LMDB to MDBX, upgrade to the new INTX interface

* Don't generate C# interface

* Appveyor include Strawberry path in %PATH%

* Mark override functions as `override`

* ERROR is a Windows macro : cannot be used as enum member

* Remove unused lambda capture

* Move donwloader under silkworm/db, remove concept(ualized) encode and rework encode functions, setup test target on silkworm/db, move some grpc/protobuf to extra_packages

* Fix some code-style issues

* Newlines at the end of file

* interfaces not required if SILKWORM_CORE_ONLY

* download_headers is C++ 17 now

* db_test is already defined in cmd/CMakeLists.txt

* Update gRPC to 1.34.0 (otherwise it doesn't build on my mac)

* Revert "Update gRPC to 1.34.0 (otherwise it doesn't build on my mac)"

This reverts commit 697432c76b897952f6a85b34c531d6b1e3b52c77.

* Upgrade protobuf for gcc 9 compatibility

* No need to generate types.grpc

* Break a long string literal to prevent Compiler Error C2026 with MSVC

Co-authored-by: Andrea Lanfranchi <andrea.lanfranchi@gmail.com>
Co-authored-by: Andrew Ashikhmin <34320705+yperbasis@users.noreply.github.com>
Co-authored-by: yperbasis <andrey.ashikhmin@gmail.com>