cmake: update conan
conan 1.60.2 doesn't work on Ubuntu 24.04 producing an error:

    ModuleNotFoundError: No module named 'imp'

because Ubuntu 24.04 has upgraded to Python 3.12 where imp is deprecated and is turned into importlib.
conan 1.60.2 doesn't support Python 3.12.